---
- name: Add apt repository for Python 3.6
  apt_repository:
    repo: ppa:jonathonf/python-3.6
- apt: update_cache=yes
- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - redis-server
    - python3.6
    - python3.6-venv
    - python3.6-dev
- name: Configure boris user
  user: name={{boris_app_user}} shell=/bin/bash home={{boris_app_user_home}} uid=550
- name: Set permissions for boris user
  file: path={{boris_app_user_home}} state=directory owner={{boris_app_user}} group=www-data mode=751
- name: Setup bashrc
  template: src=bashrc dest={{boris_app_user_home}}/.bashrc owner={{boris_app_user}}

# Clone the git repo if configured:
- name: Ensure .ssh directory exists for ssh deploy key
  file: 
    dest: "{{boris_app_user_home}}/.ssh"
    mode: 0700 
    owner: "{{boris_app_user}}" 
    state: directory
  when: boris_app_deploy_key
- name: Install ssh deploy key
  copy: 
    content: "{{ boris_app_deploy_key }}" 
    dest: "{{boris_app_user_home}}/.ssh/id_rsa"
    mode: 0600
    owner: "{{boris_app_user}}"
  when: boris_app_deploy_key
- name: Create public key file
  shell: ssh-keygen -yf {{boris_app_user_home}}/.ssh/id_rsa > {{boris_app_user_home}}/.ssh/id_rsa.pub
  args:
    creates: "{{boris_app_user_home}}/.ssh/id_rsa.pub"
  become_user: "{{boris_app_user}}"
  when: boris_app_clone_repo
- name: Check out the boris code
  git:
    repo: "{{boris_app_src}}"
    dest: "{{boris_app_dir}}"
    version: "{{boris_app_version}}"
    accept_hostkey: true
  become_user: "{{boris_app_user}}"
  when: boris_app_clone_repo

- name: Configure environment
  template: src=environ dest={{boris_app_env_file}} owner={{boris_app_user}} mode=600

- name: Create virtualenv
  pip:
    requirements: '{{boris_app_dir}}/backend/requirements.txt'
    virtualenv: '{{boris_app_python_venv_dir}}'
    virtualenv_command: /usr/bin/python3.6 -m venv
    chdir: '{{boris_app_dir}}/backend'
  become_user: "{{boris_app_user}}"
- name: Keep pip up to date
  pip:
    name: 'pip'
    virtualenv: '{{boris_app_python_venv_dir}}'
    virtualenv_command: /usr/bin/python3.6 -m venv
    state: latest
  become_user: "{{boris_app_user}}"


# Postgresql Database
- name: Configure database user for the app
  postgresql_user: name={{boris_app_db_user}} password={{boris_app_db_password}}
  become_user: postgres
- name: Configure database for the app
  postgresql_db: name={{boris_app_db_name}} owner={{boris_app_db_user}}
  become_user: postgres
- name: Enable pgcrypto extension
  postgresql_ext: name=pgcrypto db={{boris_app_db_name}}
  become_user: postgres

# Postgresql Database for testing
- name: Configure database user (testing)
  postgresql_user: name={{boris_app_testdb_user}} password={{boris_app_testdb_password}} role_attr_flags=CREATEDB
  become_user: postgres
  when: boris_include_test_environment

# nginx
- name: Install a self-signed certificate
  template:
    src=boris-self.crt
    dest=/etc/nginx/ssl/boris-self.crt
- name: Install a self-signed private key
  template:
    src=boris-self.key
    dest=/etc/nginx/ssl/boris-self.key
- name: Configure nginx
  template: src=nginx-boris.conf dest=/etc/nginx/sites-available/boris-app.conf
  notify:
    - reload nginx
- name: Install nginx config
  file: src=/etc/nginx/sites-available/boris-app.conf dest=/etc/nginx/sites-enabled/boris-app.conf state=link
  notify:
    - reload nginx
