---
- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - postgresql-{{boris_postgresql_version}}
    - postgresql-contrib-{{boris_postgresql_version}}

- name: Enable password auth over local socket
  lineinfile:
    dest="/etc/postgresql/{{boris_postgresql_version}}/main/pg_hba.conf"
    regexp='local +all +all +(password|md5|peer)'
    line='local   all             all                                     md5'
  notify:
    - reload postgres

- name: Configure an admin user for ansible etc.
  postgresql_user:
    name: "{{database_postgres_admin_user_name}}"
    role_attr_flags: SUPERUSER
    password: "{{database_postgres_admin_password}}"
    encrypted: yes
  become: true
  become_user: postgres

- name: Allow PostgreSQL connections via spiped through firewall
  ufw: rule=allow port={{postgres_spiped_port}} proto=tcp

- name: Install postgres backup script
  copy: src=backup-postgres.sh dest={{database_postgres_backup_script_file}} owner=root mode=755
- name: Create postgres backups directory
  file: path=/var/backups/postgres state=directory owner=postgres mode=700
- name: Configure PostgreSQL backup cron job
  cron:
    name: "Backup all PostgreSQL databases"
    user: postgres
    minute: "45"
    hour: "3"
    job: "{{database_postgres_backup_script_file}}"
