version: '3'
services:
  redis:
    image: "redis:4.0-alpine"
    command: >
     --requirepass devpassword 
    ports:
      - "3331:6379"
  postgres:
    image: "postgres:10.1-alpine"
    ports:
      - "3332:5432"
    environment:
     POSTGRES_PASSWORD: devpassword
     POSTGRES_USER: postgres
