version: 2
jobs:
  build:
    docker:
      - image: circleci/node:8.11.1-browsers
      - image: redis:4.0-alpine
      - image: circleci/postgres:10.1-alpine-ram
        environment:
          POSTGRES_USER: boris
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: boris_test
    environment:
      NODE_ENV: test
      BORIS_CONFIG: '{"test": {"db_port": 5432, "db_password": "testpassword", "redis_port": "6379", "redis_password": null}}'

    working_directory: ~/repo

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      
      # build static assets
      - run: npm run build

      # run tests!
      - run: npm test
