---
- name: Install required packages
  apt: name={{ item }} state=present
  with_items:
    - postgresql-{{boris_postgresql_version}}
    - postgresql-contrib-{{boris_postgresql_version}}

- name: Enable password auth over local socket
  lineinfile:
    dest="/etc/postgresql/{{boris_postgresql_version}}/main/pg_hba.conf"
    regexp='local +all +all +(password|md5|peer)'
    line='local   all             all                                     md5'
  notify:
    - reload postgres
