boris_app_mode: production
boris_app_domain: "something.apocalypsemadeeasy.com"
boris_image_tag: "latest"
boris_mailgun_api_key: "{{ lookup('file', boris_deploy_private_dir + 'credentials/mailgun_api_key') }}"
boris_app_db_host: "{{traefik_docker_apps_network_host_ip}}"  # In order to be accessible to docker containers, spiped for the DB listens on this IP instead of 127.0.0.1
boris_app_db_name: "boris_{{boris_instance_name}}"
boris_app_db_user: "boris_{{boris_instance_name}}"
boris_app_db_password: "{{ lookup('password', boris_deploy_private_dir + 'credentials/app_pgpassword length=15') }}"
boris_app_secret: "{{ lookup('password', boris_deploy_private_dir + 'credentials/app_secret length=50') }}"
boris_app_environ_dir: "/etc/boris"
boris_app_environ_file: "{{boris_app_environ_dir}}/{{boris_instance_name}}.env"


boris_config_base:
  app_domain: '{{ boris_app_domain }}'
  app_protocol: 'https'
  listen_port: 3333
  resource_url: '/s'
  mailgun_api_key: "{{ boris_mailgun_api_key }}"
  system_emails_from: "BORIS <info@apocalypsemadeeasy.com>"
  redis_host: "{{ traefik_docker_apps_network_host_ip }}"
  redis_port: "{{redis_secure_port}}"
  redis_password: "{{redis_password}}"
  redis_prefix: "boris:{{boris_instance_name}}:"
  db_host: "{{ boris_app_db_host }}"
  db_port: "{{ postgres_secure_port }}"
  db_name: "{{ boris_app_db_name }}"
  db_user: "{{ boris_app_db_user }}"
  db_password: "{{ boris_app_db_password }}"
  secret_key: "{{ boris_app_secret }}"

boris_config:
  "{{ {boris_app_mode: boris_config_base} }}"
